site_name: VMware tesztkörnyezet kialakítása
site_url: https://atiradeon86.github.io/VMware/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/atiradeon86
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/atiradeon86
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/atiradeon86

  analytics:
    provider: google
    property: G-FX3LEFY8EX
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top  
  favicon: vmware/images/favicon.png
  logo: vmware/images/vmware-logo.png
  palette:
    primary: blue
    scheme: slate
nav:
  - Tartalom:
    - index.md
    - Út a nested virtualizációhoz: vmware/page-1.md
    - Nested virtualizáció: vmware/page-2.md
    - Virutalizáció, VMware alapok: vmware/page-3.md
    - A vSphere főbb funkciói: vmware/page-4.md
    - A saját teszt környezet: vmware/page-5.md
    - Bemutató Videók : vmware/page-6.md